name: streetphotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75411
title: Street Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeeee'
    - '#bdbdbd'
    - '#000000'
    - '#7d7d7d'
    - '#373737'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
